### ISSUE TITLE
--config is not working

### ISSUE THREAD

**Issue by hujung** [mongodb/homebrew-brew#19]
I tried to install mongodb with this and follow the steps by the official guide from mongodb.
after a successful installation

when I run this command. there is no response and I can't access my localhost
```
mongod --config /usr/local/etc/mongod.conf
```
<img width="765" alt="Screen Shot 2019-09-10 at 11 23 44 AM" src="https://user-images.githubusercontent.com/37991915/64581626-78c58100-d3bd-11e9-89a4-ff5e0c8f7677.png">

<img width="728" alt="Screen Shot 2019-09-10 at 11 24 19 AM" src="https://user-images.githubusercontent.com/37991915/64581658-8da21480-d3bd-11e9-9092-4161e64fc860.png">

if I run only mongod without config option(this case, I need to make a default dir data/db)
```
mongod
```
<img width="723" alt="Screen Shot 2019-09-10 at 11 21 50 AM" src="https://user-images.githubusercontent.com/37991915/64581573-44ea5b80-d3bd-11e9-9e47-743944be84c1.png">

<img width="761" alt="Screen Shot 2019-09-10 at 11 17 43 AM" src="https://user-images.githubusercontent.com/37991915/64581420-a1994680-d3bc-11e9-9c44-e1a6ebb1591c.png">

I think when I tried to give a config then my local machine is not working or starting.

I am not sure this is my local machine issue or not, but please let me know how I can fix this.

**Comment by chasinglogic** [comment]
Hey @hujung 

Can you post the output from running the command `mongod --config /usr/local/etc/mongod.conf`?

**Comment by hendrikgaffo** [comment]
@chasinglogic I have the exact same issue after migrating from the brew `mongodb@4.0.3` formula to the `mongodb-community@4.2.0` formula on macOS Catalina (10.15 Beta).

In my case `mongod --config /usr/local/etc/mongod.conf` just returns a blank line.

Unfortunately the `mongodb` formula doesn't seem to exist anymore. Is there a way to migrate back?

**Comment by chasinglogic** [comment]
The `mongodb` formula was maintained by homebrew and has been removed.

**Comment by chasinglogic** [comment]
When you say it returns a blank line do you mean that the process exits?

If the process isn't exitting it's running and writing logs to `/usr/local/var/log/mongodb/mongo.log`.

https://github.com/mongodb/homebrew-brew/blob/master/Formula/mongodb-community.rb#L27

**Comment by hendrikgaffo** [comment]
@chasinglogic Thanks for your advice! Exactly, I meant that the process was exitting. But it was my stupidity not going through the logs first - the actual reason was a wrong version number set in `setFeatureCompatibilityVersion`, which didn't seem to work with the latest mongo version. Setting it to `"4.2"` fixed it for me.

However, this is probably not related to hujungs issue. My apologies for the confusion.

**Comment by chasinglogic** [comment]
@hendrikgaffo No problem, glad we were able to come to a solution. 

@hujung Are you having the same issue or has any of the additional context of these comments provided a solution for your problem?

**Comment by hujung** [comment]
@chasinglogic Hi I got a blank line but found this in the log file. 

![Screen Shot 2019-09-11 at 8 28 57 AM](https://user-images.githubusercontent.com/37991915/64659419-432ca080-d46e-11e9-8e10-ebb909d607d8.png)

**Comment by chasinglogic** [comment]
No problem, glad it got resolved!
