### ISSUE TITLE
How can I install mongodump and mongostore when only install mongod?

### ISSUE THREAD

**Issue by xtornasol512** [mongodb/homebrew-brew#26]
OS: MacOS X 18.7
Homebrew mongo version : mongodb-community@3.6 

I install that version on my Mac, but I notice that the tools "mongodump" and "mongostore" weren't install, what would I do?, what it is the  recommendation to install them?

**Comment by xtornasol512** [comment]
[UPDATE]
After reading some more the docs, I tried to install  mongodb-community without version, because the readme saids that bring up the tools like mongorestore, mongodump, so I typed this and works fine

```
brew install mongodb-community
brew services start mongodb/brew/mongodb-community
# Then I can use mongodump and mongorestore
```
The only issue now is , because I installed 3.6 before, if I type `mongo` appears the version `v4.2.1`but  when  I connect it with my CLI Robo 3, shows me the version `v3.6`, otherwise, everything is going okay!

**Comment by chasinglogic** [comment]
Thanks for the bug report! We're disabling Github Issues on this repository and directing users to our normal support channels. I've moved this ticket to JIRA and we're investigating it.

Moved to https://jira.mongodb.org/browse/SERVER-44895
