### ISSUE TITLE
launchctl Problem w/ Homebrew Service

### ISSUE THREAD

**Issue by utkonos** [mongodb/homebrew-brew#29]
MongoDB starts fine using `mongod --config /usr/local/etc/mongod.conf` but `brew services run mongodb-community` fails with the following error:

```
Unrecognized domain-target specifier.                                                           │
Please refer to `man launchctl` for explanation of the domain-target specifiers.                │
Usage: launchctl bootstrap <domain-target> [service-path, service-path2, ...]                   │
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /usr/local/opt/mongodb-communi│
ty/homebrew.mxcl.mongodb-community.plist` exited with 64.
```

macOS version 10.15.1
mongodb-community version 4.2.1

**Comment by chasinglogic** [comment]
Thanks for the bug report! We're disable Github Issues on this repository and directing users to our normal support channels. I've moved this ticket to JIRA and scheduled it for Triage today.

Moved to https://jira.mongodb.org/browse/SERVER-45020
