### ISSUE TITLE
Latest MongoDB v4.0.9 does not start successfully

### ISSUE THREAD

**Issue by xeroxoid** [mongodb/homebrew-brew#6]
After updating homebrew using the `mongodb/brew` tap the installed version `4.0.9` will not start via brew services.

The error thrown is:

```Error: mongodb-community: uninitialized constant #<Class:0x00007ff189061008>::Gem```

When running `brew doctor` the following output is shown:

```Warning: Some installed formulae are not readable:
  mongodb-community: uninitialized constant #<Class:0x00007f9509aca620>::Gem
```

To reproduce:
```brew tap mongodb/brew
brew install mongodb-community@4.0
```

It works as expected when using `mongodb-community@3.6`

**Comment by ianvonholt** [comment]
I'm experiencing this issue as well. I have a fresh install of macOS Mojave 10.14.5 Beta (18F131a)


Console output of install and subsequent attempt to run:
```
Ranku-MBP:~ Narwhal$ brew install mongodb-community@4.0
==> Installing mongodb-community from mongodb/brew
==> Downloading https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-4.0.9.tgz
######################################################################## 100.0%
==> Caveats
To have launchd start mongodb/brew/mongodb-community now and restart at login:
  brew services start mongodb/brew/mongodb-community
Or, if you don't want/need a background service you can just run:
  mongod --config /usr/local/etc/mongod.conf
==> Summary
🍺  /usr/local/Cellar/mongodb-community/4.0.9: 20 files, 221.0MB, built in 10 seconds
==> `brew cleanup` has not been run in 30 days, running now...
Ranku-MBP:~ Narwhal$ brew services start mongodb/brew/mongodb-community
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 17 (delta 0), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), done.
Tapped 1 command (50 files, 62.6KB).
Error: mongodb/brew/mongodb-community: uninitialized constant #<Class:0x00007fdc7e8eac58>::Gem
```

Starting mongodb manually seems to work fine with the following:
```
mongod --config /usr/local/etc/mongod.conf
```

**Comment by ianvonholt** [comment]
An update, the following will automatically successfully launch MongoDB Community Edition at macOS boot:

```
ln -sfv /usr/local/opt/mongodb-community/*.plist ~/Library/LaunchAgents
```
```
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb-community.plist
```

**Comment by codepope** [comment]
+1 - hit this issue too 

Other reports - https://stackoverflow.com/questions/55988684/brew-services-start-mongodb-community4-0-fails-uninitialized-constant

**Comment by hemedani** [comment]
I have the same problem

**Comment by lincoln-b** [comment]
I have fixed the issue on my machine by editing this file: `/usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community.rb`

I added `require 'rubygems'` on line 6, and it works like a charm. Going to try to prepare a pull request so this gets fixed quicker.

**Comment by davidlares** [comment]
Reporting the same problem even with the 3.6 version of it.

If you try to start manually also the `mongod` command it's not recognized by the tap.

**Comment by chasinglogic** [comment]
Hey everyone, thanks for reporting the issue and thanks @lincoln-b for submitting a PR.

Just wanted to give the update that I'm looking at the PR and thanks to lincoln-b's work this should be fixed soon.

**Comment by designalchemy** [comment]
No tests to prevent this kinda of thing 😅?

**Comment by chasinglogic** [comment]
I'm going to close this issue now that we've merged @lincoln-b's fix. It appears to be working now.

@davidlares Since the original poster advised they had no issues with 3.6 it's possible that you're running into a different issue and if so can you open another issue? It seems to me that your mongod is not in the `$PATH` which it shouldn't be by default according to the brew install output:

```
==> Caveats
mongodb-community@3.6 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have mongodb-community@3.6 first in your PATH run:
  echo 'export PATH="/usr/local/opt/mongodb-community@3.6/bin:$PATH"' >> ~/.zshrc
```
